{
  "latest_version": [
    "3.6.3"
  ],
  "meta": {
    "description": "Zope 3 exception views",
    "homepage": "http://pypi.python.org/pypi/zope.app.exception",
    "license": "ZPL 2.1"
  },
  "versions": [
    {
      "3.4.0": {
        "sha256": "de7dfd1d1a90ba58d1a3efcb1933f44a1190b701f960dc7f99c82c9cec2cb024",
        "url": "https://files.pythonhosted.org/packages/83/3c/54e0629d335f2ab595df749be90e96c8826d932158c784f922f5f02ff2cf/zope.app.exception-3.4.0.tar.gz"
      },
      "3.4.0a1": {
        "sha256": "b1e753c5bc7b94441e88cd680d08fcde7c53a80c4f3fe2c2ba2d32d3d13413ce",
        "url": "https://files.pythonhosted.org/packages/81/85/3485752e0b2d52ef261f34321648f8171260d0f00635338abb7af8d16ea3/zope.app.exception-3.4.0a1.tar.gz"
      },
      "3.4.1": {
        "sha256": "49fd3704e171bdb444330c1fc880355968fac2f2ab7d05ac437f6eecea334c60",
        "url": "https://files.pythonhosted.org/packages/94/62/b0dd485dd4fbf471f87b5615893d4bc6a1de5db7e54ad6ed69ac8da56a92/zope.app.exception-3.4.1.tar.gz"
      },
      "3.4.2": {
        "sha256": "7295f1e2a4cd2c09bb6e68c61c9739b101343fa170654cd8808c6582b46bf083",
        "url": "https://files.pythonhosted.org/packages/0a/e1/3e184e81ae43d1bbf6cb3089216300c76eabe1639e57e9bcd22c10b5d318/zope.app.exception-3.4.2.tar.gz"
      },
      "3.5.0": {
        "sha256": "60d1ccc1fbf0635fe072f7e3544fe7d3e6d7706f2221d97582baca149565576e",
        "url": "https://files.pythonhosted.org/packages/01/3a/659b3f16d0129107008f3fb0016b17a249d9c4af7a3721e9444b12acb27a/zope.app.exception-3.5.0.tar.gz"
      },
      "3.6.0": {
        "sha256": "640dc6c43904a917b342f699a18e9ec67e351b6d83ee5dad51eaac25fa2823f8",
        "url": "https://files.pythonhosted.org/packages/68/59/ac76b602ef88b5cb01f6054bdd4cb310403219e9048e41b3184c2511e1b8/zope.app.exception-3.6.0.tar.gz"
      },
      "3.6.1": {
        "sha256": "6a05cd72958605f08238d8c33ee452a0482e2e0dc31e4a98f744c1534a430c2a",
        "url": "https://files.pythonhosted.org/packages/07/90/74dce6107fd14ef5df2cf18e33f92e4a1b827081a55281df3b01b235679d/zope.app.exception-3.6.1.tar.gz"
      },
      "3.6.2": {
        "sha256": "522ffe2b8636c4be611477b8ac26bd105a259ad3090725ba4ee9d4444fb0c254",
        "url": "https://files.pythonhosted.org/packages/03/66/8c9be4b61fb7425204285e575e372c5e8c5c0099f5d3894080419eea5976/zope.app.exception-3.6.2.tar.gz"
      },
      "3.6.3": {
        "sha256": "4689647ce1ff1104ea9e451ee4c0a7bd0be0c0bbbcb6a16039f8052f13feeb63",
        "url": "https://files.pythonhosted.org/packages/4d/91/30cf40e8ba9a25600af8c2a896c61a7f3febbda6025abfc69babb769d6ed/zope.app.exception-3.6.3.tar.gz"
      }
    }
  ]
}