{
  "latest_version": [
    "3.5.3"
  ],
  "meta": {
    "description": "Error reporting utility management UI for Zope3",
    "homepage": "http://pypi.python.org/pypi/zope.app.error",
    "license": "ZPL 2.1"
  },
  "versions": {
    "3.4.0": {
      "sha256": "aa1cd3ee14905392e8b83f8b700d44dac29d4364a90acc7b9bc059d7b292c597",
      "url": "https://files.pythonhosted.org/packages/7d/d4/a35d953d07f0dec24bfebbf16bc4381cd205b3a8357eb34cd46123152435/zope.app.error-3.4.0.zip"
    },
    "3.4.0a1": {
      "sha256": "3535dc2302f01dc7dacf227b92d351cd9941a203852f66dcdbfe8ccc8b4122f4",
      "url": "https://files.pythonhosted.org/packages/a7/ff/67bea82c8bafc901c84a9a1e9067cc4eb888c2028a2756f308b51ace21a7/zope.app.error-3.4.0a1.tar.gz"
    },
    "3.4.1": {
      "sha256": "622204ff13b23bac460ab5792922825191b27e428527db65567780cf962ef588",
      "url": "https://files.pythonhosted.org/packages/80/4a/ab6338c84cc611602bc430c607e90e7a6fc780b7c3398bd7ed50ce3c6511/zope.app.error-3.4.1.tar.gz"
    },
    "3.5.0": {
      "sha256": "d97a6184190fd1b16cae1be8d92eff2fb03a131b1bb36a5403e73e62b7f85383",
      "url": "https://files.pythonhosted.org/packages/03/52/db3b083e2484db575ebb0402af3ee61dc27e2ad24244227f7fd9bdcc388c/zope.app.error-3.5.0.zip"
    },
    "3.5.1": {
      "sha256": "22cfdcf967117fc95bc7afd3294decc8fa465882e8a3daa7d2d3bbd4436493dc",
      "url": "https://files.pythonhosted.org/packages/d0/4c/26a2fc613adda7e24ef77a7230e285c854e47b74cc9b35ae6945f9685885/zope.app.error-3.5.1.tar.gz"
    },
    "3.5.2": {
      "sha256": "84afab259df90d1e79528ae2d6e5bffc8b89500d3e3f4703226ba7b3479ee744",
      "url": "https://files.pythonhosted.org/packages/fa/17/208adcd9a70aa3793a0772ab8dfb2e25c56241ababbe0a43e0730fd5db99/zope.app.error-3.5.2.tar.gz"
    },
    "3.5.3": {
      "sha256": "795ce65c66a23af15149ed6d8cfb68eac2d40af00943e21213b612453d959bbc",
      "url": "https://files.pythonhosted.org/packages/31/fa/20c22990fb42fe7524c090a37c0cc316749d8d2a2ca0e116621176e99094/zope.app.error-3.5.3.tar.gz"
    }
  }
}